name: Test Build

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # Silence/enable required native builds (seen as "Ignored build scripts: esbuild")
      - name: Approve pnpm builds
        run: pnpm approve-builds esbuild

      - name: Install deps
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Test build
        env:
          NODE_ENV: production
        run: pnpm run build